//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MInfoSet
    {
        public long Id { get; set; }
        public string SourceName { get; set; }
        public string Source { get; set; }
        public string IndependentSource { get; set; }
        public Nullable<System.DateTime> SourceCreateDate { get; set; }
        public System.DateTime SourceCollectionDate { get; set; }
        public string SourceRemark { get; set; }
        public string Area { get; set; }
    }
}
