//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmplete
    {
        public System.Guid ID { get; set; }
        public string ParamKey { get; set; }
        public string ParamValue { get; set; }
        public string ParamRemarks { get; set; }
        public short ParamVersion { get; set; }
    }
}
